In [13]:
import pandas as pd


url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'

data = pd.read_csv(url)

In [2]:
data['Sex'].unique()

array(['female', 'male'], dtype=object)

In [5]:
data['Sex'].value_counts()

male      851
female    462
Name: Sex, dtype: int64

In [7]:
data['PClass'].value_counts()

3rd    711
1st    322
2nd    279
*        1
Name: PClass, dtype: int64

In [8]:
data['PClass'].unique()

array(['1st', '2nd', '*', '3rd'], dtype=object)

Methods *isnull* and *notnull* returns boolean values, if is there a value or not

In [10]:
data[data['Age'].isnull()].head(3)

                            Name PClass  Age     Sex  Survived  SexCode
12  Aubert, Mrs Leontine Pauline    1st  NaN  female         1        1
13      Barkworth, Mr Algernon H    1st  NaN    male         1        0
14            Baumann, Mr John D    1st  NaN    male         0        0

In [11]:
data['Sex'].replace('female', NaN)

NameError: ignored

In [14]:
from numpy import NaN


data['Sex'].replace('female', NaN)

0        NaN
1        NaN
2       male
3        NaN
4       male
        ...
1308    male
1309    male
1310    male
1311    male
1312    male
Name: Sex, Length: 1313, dtype: object