In [2]:
import pandas as pd


url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'

data = pd.read_csv(url)

In [6]:
data.head(5)

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0

In [7]:
data.drop('Age', axis=1).head(5)

,Name,PClass,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,female,1,1
1,"Allison, Miss Helen Loraine",1st,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,female,0,1
4,"Allison, Master Hudson Trevor",1st,male,1,0

In [8]:
data.drop(['Age', 'PClass'], axis=1).head(5)

                                            Name     Sex  Survived  SexCode
0                   Allen, Miss Elisabeth Walton  female         1        1
1                    Allison, Miss Helen Loraine  female         0        1
2            Allison, Mr Hudson Joshua Creighton    male         0        0
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)  female         0        1
4                  Allison, Master Hudson Trevor    male         1        0

In [10]:
data.drop(data.columns[0], axis=1).head(5)  # if a column is not nammed

  PClass    Age     Sex  Survived  SexCode
0    1st  29.00  female         1        1
1    1st   2.00  female         0        1
2    1st  30.00    male         0        0
3    1st  25.00  female         0        1
4    1st   0.92    male         1        0

In order to delete duplicates in the data frame we use *drop_duplicates* that as default saves first unique values but we can control it by *keep* parameter. Usually we search duplicates in a subset of the data frame and for the reason we use *subset* parameter of the method.

In [15]:
data.drop_duplicates(subset=['Sex'], keep='last')

                     Name PClass   Age     Sex  Survived  SexCode
1307  Zabour, Miss Tamini    3rd   NaN  female         0        1
1312       Zimmerman, Leo    3rd  29.0    male         0        0

In [17]:
data.head(5)

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0

In [18]:
data.duplicated(subset=['Sex']).head(5)

0    False
1     True
2    False
3     True
4     True
dtype: bool